### PR TITLE
More common files for whitelist

### PR DESCRIPTION
**Pull request by rinkuyadav999**

### CODE REVIEW

**Comment by pattonwebz** [comment]
Define list of other common whitelist items, decide how common `init.php` is within themes

**Comment by jrfnl** [comment]
For now, I will add unit tests to this PR and remove `init.php` so this PR can be merged.

Once @pattonwebz has run a check on the Theme repo, a new PR can be opened to add more files to be whitelisted if needed.

**Comment by jrfnl** [comment]
Hmm... I've just had a closer look at the sniff and this PR in particular.

The `$file_whitelist` property whitelists files from which it is expected that `include`/`require` calls are made.
It does not whitelist the names of files which are expected to be included/required.

In other words, this PR will need more work than expected.
In my opinion, a separate property will need to be introduced for files which are expected to be included/required and logic will need to be added to the sniff to handle this.
This logic would also need to take into account that these files can be placed in subdirectories.

@rinkuyadav999 Would you like to update the sniff for this ?
If not - and as the PR which is needed will be considerably different from the original PR -, I would suggest closing this ticket in favour of a new PR which introduces the concept of "files which are allowed to be included".

**Comment by justintadlock** [comment]
`functions.php` is already loaded by WP.  `class-tgm-plugin-activation.php` is pretty common.

I can't think of any common files in particular to whitelist.  Themes are so vastly different in which file names that they include/require that I'm not sure it'd be worthwhile.

If you could do partial matches, it might work.  For example, any file that begins with `class-` would likely be a class file, for example.

**Comment by justintadlock** [comment]
There doesn't seem to be much interest in this ticket based on the team meeting.  We don't think it's worth pursuing.

Meeting: https://wordpress.slack.com/archives/C02RP4Y3K/p1528822802001090

**Pull request closed without merging**
