### PR TITLE
Improve plugin-territory list of block-related functions

### PR DESCRIPTION
**Pull request by aristath**
The current rule disallows adding patterns, styles, scripts etc.

This change tweaks the list of plugin-territory functions to the ones that should actually only be in plugins

### CODE REVIEW

**Review by dingo-d — APPROVED** [review]

**Comment by dingo-d** [comment]
Some dependencies are not right. I can check that later. @jrfnl Do you maybe know what's this about?

**Comment by jrfnl** [comment]
> Some dependencies are not right. I can check that later. @jrfnl Do you maybe know what's this about?

Yes, there are a couple of things going on:
1. TRTCS uses WPCS `dev-develop` in Travis, which is now `3.0-dev`.
2. Until PHPCSUtils 1.0 is released, the `PHPCSUtils` dependency is regarded as `dev` and the TRTCS Composer config does not allow for `dev` dependencies (`minimum_stability`)
3. Aside from that, the code in TRTCS expects WPCS 2.x, not 3.x.

I suggest switching to WPCS `dev-master` for Travis for the time being and adding a single "allowed to fail" build against WPCS `dev-develop`.

**Comment by dingo-d** [comment]
@aristath Can you rebase this PR as well so that we can check the GH Actions checks?

**Comment by aristath** [comment]
Done

**Pull request merged**
